import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from '../components/layout/nav';
import Footer from '../components/layout/footer';

import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-day-picker/dist/style.css';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
