version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3002:3002" # Expose the frontend on port 3000
    volumes:
      - ./frontend:/app # Mount the frontend code into the container
      - /app/node_modules # Use a volume for node_modules to avoid overriding the node_modules with the host's
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001" # Expose the backend on port 5000
    volumes:
      - ./backend:/app # Mount the backend code into the container
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432" # Expose PostgreSQL default port
    environment:
      POSTGRES_DB: petdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Persist database data

  devcontainer:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14
    volumes:
      - ./frontend:/app
      - ./backend:/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - frontend
      - backend
      - db
