name: JavaScript CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths-ignore:
      - "**/*.md" # Ignore markdown files, adjust as needed

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies and Run ESLint
        run: |
          cd backend
          npm install
          npx eslint .

      - name: Security Scan
        run: |
          cd backend
          npm audit

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies and Run ESLint
        run: |
          cd frontend
          npm install
          npx eslint .

      - name: Security Scan
        run: |
          cd frontend
          npm audit
