name: JavaScript CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Backend Dependencies and Run ESLint
        run: |
          cd backend
          npm install
          npx eslint .

      - name: Security Scan
        run: |
          cd backend
          npm audit

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Frontend Dependencies and Run ESLint
        run: |
          cd frontend
          npm install
          npx eslint .

      - name: Security Scan
        run: |
          cd frontend
          npm audit
