name: Lint on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        app: [frontend, backend]
        include:
          - app: frontend
            path: 'frontend/**'
          - app: backend
            path: 'backend/**'
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version here

    - name: Install Dependencies
      run: cd ${{ matrix.app }} && npm install

    - name: Run Lint
      run: cd ${{ matrix.app }} && npm run lint
